services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user -d cinema_db"]
      interval: 5s 
      timeout: 5s
      retries: 5 
      start_period: 10s 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/cinema_db?schema=public
    depends_on: 
      db:
        condition: service_healthy 
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules

volumes:
  db_data: